version: '3.8'

services:
  cortex-ai-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cortex_ai_suite
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - NVIDIA_BASE_URL=https://integrate.api.nvidia.com/v1
      - DEFAULT_CHAT_MODEL=meta/llama-3.1-8b-instruct
    volumes:
      - ./backend/app:/app/app
      - ./frontend:/app/frontend
    restart: unless-stopped
